### PR TITLE
Fix: remove redundant console.log

### PR DESCRIPTION
**Pull request by jfkz**
Hi! I found out this package well written, but found strange behavior when try to do querySelection. After little search I found console.log (probably added for debug purposes), but it was uncontrollable and little messy =)

So I did patch to fix this problem. Please review.

### CODE REVIEW

**Comment by bstag** [comment]
@ChukwuEmekaAjah Can we get this merged and pushed. Love using this just need to stop it from filling my console with logs.

**Comment by ChukwuEmekaAjah** [comment]
Okay, I would look into it and make necessary amends.

**Comment by ChukwuEmekaAjah** [comment]
It's not a bug fix. Why are you tagging it as such? Also what's the difference between module.exports and exports.default? How does using one or the other affect backward compatibility with older versions of NodeJs runtimes? Thanks for your most anticipated response.

**Comment by jfkz** [comment]
Hi, @ChukwuEmekaAjah !
Sorry for slow answering. That's how `tsc` compiled code, i didn't check their output. My `tsc` version is higher than you used before, but i rollback changes by hand to minimize impact on your code.

**Pull request closed without merging**
